//
// OCROperationsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class OCROperationsAPI {

    /**
     Process check image with OCR and extract structured data
     
     - parameter body: (body)  
     - returns: CheckModelOcrResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func processCheckOcr(body: URL) async throws -> CheckModelOcrResponse {
        return try await processCheckOcrWithRequestBuilder(body: body).execute().body
    }

    /**
     Process check image with OCR and extract structured data
     - POST /ocr/checks
     - Processes a check image using Mistral OCR and extracts structured check data including amount, payee, payer, bank info, and routing details.
     - parameter body: (body)  
     - returns: RequestBuilder<CheckModelOcrResponse> 
     */
    open class func processCheckOcrWithRequestBuilder(body: URL) -> RequestBuilder<CheckModelOcrResponse> {
        let localVariablePath = "/ocr/checks"
        let localVariableURLString = NolockOCRClientAPI.basePath + localVariablePath
        let localVariableParameters = ["body": body]

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/octet-stream",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckModelOcrResponse>.Type = NolockOCRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Process receipt image with OCR and extract structured data
     
     - parameter body: (body)  
     - returns: ReceiptModelOcrResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func processReceiptOcr(body: URL) async throws -> ReceiptModelOcrResponse {
        return try await processReceiptOcrWithRequestBuilder(body: body).execute().body
    }

    /**
     Process receipt image with OCR and extract structured data
     - POST /ocr/receipts
     - Processes a receipt image using Mistral OCR and extracts structured receipt data including merchant info, totals, items, and payment details.
     - parameter body: (body)  
     - returns: RequestBuilder<ReceiptModelOcrResponse> 
     */
    open class func processReceiptOcrWithRequestBuilder(body: URL) -> RequestBuilder<ReceiptModelOcrResponse> {
        let localVariablePath = "/ocr/receipts"
        let localVariableURLString = NolockOCRClientAPI.basePath + localVariablePath
        let localVariableParameters = ["body": body]

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/octet-stream",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReceiptModelOcrResponse>.Type = NolockOCRClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
