//
// CheckModelOcrResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckModelOcrResponse: Codable, JSONEncodable, Hashable {

    public var modelData: Check?
    public var processingTime: String?
    public var success: Bool?
    public var error: String?

    public init(modelData: Check? = nil, processingTime: String? = nil, success: Bool? = nil, error: String? = nil) {
        self.modelData = modelData
        self.processingTime = processingTime
        self.success = success
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case modelData
        case processingTime
        case success
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(modelData, forKey: .modelData)
        try container.encodeIfPresent(processingTime, forKey: .processingTime)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

