//
// CheckMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckMetadata: Codable, JSONEncodable, Hashable {

    /** Confidence score of the extraction */
    public var confidenceScore: Double?
    /** Identifier of the source image */
    public var sourceImageId: String?
    /** Provider used for OCR */
    public var ocrProvider: String?
    /** List of warnings from the extraction process */
    public var warnings: [String]?

    public init(confidenceScore: Double? = nil, sourceImageId: String? = nil, ocrProvider: String? = nil, warnings: [String]? = nil) {
        self.confidenceScore = confidenceScore
        self.sourceImageId = sourceImageId
        self.ocrProvider = ocrProvider
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case confidenceScore
        case sourceImageId
        case ocrProvider
        case warnings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(confidenceScore, forKey: .confidenceScore)
        try container.encodeIfPresent(sourceImageId, forKey: .sourceImageId)
        try container.encodeIfPresent(ocrProvider, forKey: .ocrProvider)
        try container.encodeIfPresent(warnings, forKey: .warnings)
    }
}

