//
// Check.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Check: Codable, JSONEncodable, Hashable {

    /** Check number or identifier */
    public var checkNumber: String?
    /** Date on the check (ISO 8601 format when transmitted as string) */
    public var date: Date?
    /** Person or entity to whom the check is payable */
    public var payee: String?
    /** Person or entity who wrote/signed the check */
    public var payer: String?
    /** Dollar amount of the check - converted from string to decimal for C# type safety */
    public var amount: Double?
    /** Written amount text on the check */
    public var amountText: String?
    /** Memo or note on the check */
    public var memo: String?
    /** Name of the bank issuing the check */
    public var bankName: String?
    /** Bank routing number (9 digits) */
    public var routingNumber: String?
    /** Bank account number */
    public var accountNumber: String?
    public var checkType: CheckType?
    public var accountType: BankAccountType?
    /** Whether the check appears to be signed */
    public var signature: Bool?
    /** Text of the signature if readable */
    public var signatureText: String?
    /** Fractional code on the check (alternative routing identifier) */
    public var fractionalCode: String?
    /** Full MICR (Magnetic Ink Character Recognition) line on the bottom of check */
    public var micrLine: String?
    public var metadata: CheckMetadata?
    /** Overall confidence score of the extraction */
    public var confidence: Double?
    /** Indicates if the input appears to be a valid check image. False if the system has detected potential hallucinations */
    public var isValidInput: Bool?

    public init(checkNumber: String? = nil, date: Date? = nil, payee: String? = nil, payer: String? = nil, amount: Double? = nil, amountText: String? = nil, memo: String? = nil, bankName: String? = nil, routingNumber: String? = nil, accountNumber: String? = nil, checkType: CheckType? = nil, accountType: BankAccountType? = nil, signature: Bool? = nil, signatureText: String? = nil, fractionalCode: String? = nil, micrLine: String? = nil, metadata: CheckMetadata? = nil, confidence: Double? = nil, isValidInput: Bool? = nil) {
        self.checkNumber = checkNumber
        self.date = date
        self.payee = payee
        self.payer = payer
        self.amount = amount
        self.amountText = amountText
        self.memo = memo
        self.bankName = bankName
        self.routingNumber = routingNumber
        self.accountNumber = accountNumber
        self.checkType = checkType
        self.accountType = accountType
        self.signature = signature
        self.signatureText = signatureText
        self.fractionalCode = fractionalCode
        self.micrLine = micrLine
        self.metadata = metadata
        self.confidence = confidence
        self.isValidInput = isValidInput
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case checkNumber
        case date
        case payee
        case payer
        case amount
        case amountText
        case memo
        case bankName
        case routingNumber
        case accountNumber
        case checkType
        case accountType
        case signature
        case signatureText
        case fractionalCode
        case micrLine
        case metadata
        case confidence
        case isValidInput
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(checkNumber, forKey: .checkNumber)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(payee, forKey: .payee)
        try container.encodeIfPresent(payer, forKey: .payer)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(amountText, forKey: .amountText)
        try container.encodeIfPresent(memo, forKey: .memo)
        try container.encodeIfPresent(bankName, forKey: .bankName)
        try container.encodeIfPresent(routingNumber, forKey: .routingNumber)
        try container.encodeIfPresent(accountNumber, forKey: .accountNumber)
        try container.encodeIfPresent(checkType, forKey: .checkType)
        try container.encodeIfPresent(accountType, forKey: .accountType)
        try container.encodeIfPresent(signature, forKey: .signature)
        try container.encodeIfPresent(signatureText, forKey: .signatureText)
        try container.encodeIfPresent(fractionalCode, forKey: .fractionalCode)
        try container.encodeIfPresent(micrLine, forKey: .micrLine)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(confidence, forKey: .confidence)
        try container.encodeIfPresent(isValidInput, forKey: .isValidInput)
    }
}

