//
// MerchantInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MerchantInfo: Codable, JSONEncodable, Hashable {

    /** Name of the merchant or store */
    public var name: String?
    /** Physical address of the merchant */
    public var address: String?
    /** Contact phone number */
    public var phone: String?
    /** Website URL */
    public var website: String?
    /** Tax identification number (VAT/GST ID) */
    public var taxId: String?
    /** Store or branch identifier */
    public var storeId: String?
    /** Name of the store chain if applicable */
    public var chainName: String?

    public init(name: String? = nil, address: String? = nil, phone: String? = nil, website: String? = nil, taxId: String? = nil, storeId: String? = nil, chainName: String? = nil) {
        self.name = name
        self.address = address
        self.phone = phone
        self.website = website
        self.taxId = taxId
        self.storeId = storeId
        self.chainName = chainName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case address
        case phone
        case website
        case taxId
        case storeId
        case chainName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(website, forKey: .website)
        try container.encodeIfPresent(taxId, forKey: .taxId)
        try container.encodeIfPresent(storeId, forKey: .storeId)
        try container.encodeIfPresent(chainName, forKey: .chainName)
    }
}

