//
// ReceiptPaymentMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReceiptPaymentMethod: Codable, JSONEncodable, Hashable {

    /** Payment method */
    public var method: String?
    /** Type of card - can be enum or string for flexibility */
    public var cardType: String?
    /** Last 4 digits of payment card */
    public var lastDigits: String?
    /** Amount paid with this method - converted from string to decimal for C# type safety */
    public var amount: Double?
    /** Payment transaction ID */
    public var transactionId: String?

    public init(method: String? = nil, cardType: String? = nil, lastDigits: String? = nil, amount: Double? = nil, transactionId: String? = nil) {
        self.method = method
        self.cardType = cardType
        self.lastDigits = lastDigits
        self.amount = amount
        self.transactionId = transactionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case method
        case cardType
        case lastDigits
        case amount
        case transactionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(cardType, forKey: .cardType)
        try container.encodeIfPresent(lastDigits, forKey: .lastDigits)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(transactionId, forKey: .transactionId)
    }
}

