//
// ReceiptTotals.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReceiptTotals: Codable, JSONEncodable, Hashable {

    /** Pre-tax total amount */
    public var subtotal: Double?
    /** Total tax amount */
    public var tax: Double?
    /** Tip/gratuity amount */
    public var tip: Double?
    /** Total discount amount */
    public var discount: Double?
    /** Final total amount including tax, tip, and adjusting for discounts */
    public var total: Double?

    public init(subtotal: Double? = nil, tax: Double? = nil, tip: Double? = nil, discount: Double? = nil, total: Double? = nil) {
        self.subtotal = subtotal
        self.tax = tax
        self.tip = tip
        self.discount = discount
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subtotal
        case tax
        case tip
        case discount
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(subtotal, forKey: .subtotal)
        try container.encodeIfPresent(tax, forKey: .tax)
        try container.encodeIfPresent(tip, forKey: .tip)
        try container.encodeIfPresent(discount, forKey: .discount)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

