//
// ReceiptTaxItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReceiptTaxItem: Codable, JSONEncodable, Hashable {

    /** Name of tax (e.g., 'VAT', 'GST', 'Sales Tax') */
    public var taxName: String?
    /** Type of tax - can be enum or string for flexibility */
    public var taxType: String?
    /** Tax rate as decimal (e.g., 0.07 for 7%) - converted from string to decimal for C# type safety */
    public var taxRate: Double?
    /** Tax amount - converted from string to decimal for C# type safety */
    public var taxAmount: Double?

    public init(taxName: String? = nil, taxType: String? = nil, taxRate: Double? = nil, taxAmount: Double? = nil) {
        self.taxName = taxName
        self.taxType = taxType
        self.taxRate = taxRate
        self.taxAmount = taxAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taxName
        case taxType
        case taxRate
        case taxAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(taxName, forKey: .taxName)
        try container.encodeIfPresent(taxType, forKey: .taxType)
        try container.encodeIfPresent(taxRate, forKey: .taxRate)
        try container.encodeIfPresent(taxAmount, forKey: .taxAmount)
    }
}

