//
// Receipt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Receipt: Codable, JSONEncodable, Hashable {

    public var merchant: MerchantInfo?
    /** Receipt or invoice number */
    public var receiptNumber: String?
    /** Type of receipt */
    public var receiptType: String?
    /** Date and time of transaction (ISO 8601 format when transmitted as string) */
    public var timestamp: Date?
    /** Method of payment - can be enum or string for flexibility */
    public var paymentMethod: String?
    public var totals: ReceiptTotals?
    /** ISO 4217 currency code (3-letter codes like USD, EUR, GBP) */
    public var currency: String?
    /** List of line items on the receipt */
    public var items: [ReceiptLineItem]?
    /** Breakdown of taxes */
    public var taxes: [ReceiptTaxItem]?
    /** Details about payment methods used */
    public var payments: [ReceiptPaymentMethod]?
    /** Additional notes or comments */
    public var notes: [String]?
    public var metadata: ReceiptMetadata?
    /** Overall confidence score of the extraction */
    public var confidence: Double?
    /** Indicates if the input appears to be a valid receipt image. False if the system has detected potential hallucinations */
    public var isValidInput: Bool?

    public init(merchant: MerchantInfo? = nil, receiptNumber: String? = nil, receiptType: String? = nil, timestamp: Date? = nil, paymentMethod: String? = nil, totals: ReceiptTotals? = nil, currency: String? = nil, items: [ReceiptLineItem]? = nil, taxes: [ReceiptTaxItem]? = nil, payments: [ReceiptPaymentMethod]? = nil, notes: [String]? = nil, metadata: ReceiptMetadata? = nil, confidence: Double? = nil, isValidInput: Bool? = nil) {
        self.merchant = merchant
        self.receiptNumber = receiptNumber
        self.receiptType = receiptType
        self.timestamp = timestamp
        self.paymentMethod = paymentMethod
        self.totals = totals
        self.currency = currency
        self.items = items
        self.taxes = taxes
        self.payments = payments
        self.notes = notes
        self.metadata = metadata
        self.confidence = confidence
        self.isValidInput = isValidInput
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchant
        case receiptNumber
        case receiptType
        case timestamp
        case paymentMethod
        case totals
        case currency
        case items
        case taxes
        case payments
        case notes
        case metadata
        case confidence
        case isValidInput
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(merchant, forKey: .merchant)
        try container.encodeIfPresent(receiptNumber, forKey: .receiptNumber)
        try container.encodeIfPresent(receiptType, forKey: .receiptType)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(paymentMethod, forKey: .paymentMethod)
        try container.encodeIfPresent(totals, forKey: .totals)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(taxes, forKey: .taxes)
        try container.encodeIfPresent(payments, forKey: .payments)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(confidence, forKey: .confidence)
        try container.encodeIfPresent(isValidInput, forKey: .isValidInput)
    }
}

