//
// ReceiptLineItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReceiptLineItem: Codable, JSONEncodable, Hashable {

    /** Item description or name */
    public var description: String?
    /** Stock keeping unit or product code */
    public var sku: String?
    /** Quantity purchased */
    public var quantity: Double?
    /** Unit of measurement - can be enum or string for flexibility */
    public var unit: String?
    /** Price per unit - converted from string to decimal for C# type safety */
    public var unitPrice: Double?
    /** Total price for this line item - converted from string to decimal for C# type safety */
    public var totalPrice: Double?
    /** Whether the item was discounted */
    public var discounted: Bool?
    /** Amount of discount applied - converted from string to decimal for C# type safety */
    public var discountAmount: Double?
    /** Product category */
    public var category: String?

    public init(description: String? = nil, sku: String? = nil, quantity: Double? = nil, unit: String? = nil, unitPrice: Double? = nil, totalPrice: Double? = nil, discounted: Bool? = nil, discountAmount: Double? = nil, category: String? = nil) {
        self.description = description
        self.sku = sku
        self.quantity = quantity
        self.unit = unit
        self.unitPrice = unitPrice
        self.totalPrice = totalPrice
        self.discounted = discounted
        self.discountAmount = discountAmount
        self.category = category
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case sku
        case quantity
        case unit
        case unitPrice
        case totalPrice
        case discounted
        case discountAmount
        case category
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(unit, forKey: .unit)
        try container.encodeIfPresent(unitPrice, forKey: .unitPrice)
        try container.encodeIfPresent(totalPrice, forKey: .totalPrice)
        try container.encodeIfPresent(discounted, forKey: .discounted)
        try container.encodeIfPresent(discountAmount, forKey: .discountAmount)
        try container.encodeIfPresent(category, forKey: .category)
    }
}

