//
// ReceiptMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReceiptMetadata: Codable, JSONEncodable, Hashable {

    /** Confidence score of the extraction */
    public var confidenceScore: Double?
    /** ISO currency code detected */
    public var currency: String?
    /** ISO language code of the receipt */
    public var languageCode: String?
    /** Time zone identifier */
    public var timeZone: String?
    public var receiptFormat: ReceiptFormat?
    /** Identifier of the source image */
    public var sourceImageId: String?
    /** List of warnings from the extraction process */
    public var warnings: [String]?

    public init(confidenceScore: Double? = nil, currency: String? = nil, languageCode: String? = nil, timeZone: String? = nil, receiptFormat: ReceiptFormat? = nil, sourceImageId: String? = nil, warnings: [String]? = nil) {
        self.confidenceScore = confidenceScore
        self.currency = currency
        self.languageCode = languageCode
        self.timeZone = timeZone
        self.receiptFormat = receiptFormat
        self.sourceImageId = sourceImageId
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case confidenceScore
        case currency
        case languageCode
        case timeZone
        case receiptFormat
        case sourceImageId
        case warnings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(confidenceScore, forKey: .confidenceScore)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(languageCode, forKey: .languageCode)
        try container.encodeIfPresent(timeZone, forKey: .timeZone)
        try container.encodeIfPresent(receiptFormat, forKey: .receiptFormat)
        try container.encodeIfPresent(sourceImageId, forKey: .sourceImageId)
        try container.encodeIfPresent(warnings, forKey: .warnings)
    }
}

