// APIs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
open class NolockOCRClientAPI {
    public static var basePath = "http://localhost"
    public static var customHeaders: [String: String] = [:]
    public static var credential: URLCredential?

    // Automatically configure authentication for iOS/macOS apps
    public static var requestBuilderFactory: RequestBuilderFactory = {
        #if canImport(StoreKit)
        if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *) {
            // Automatically use StoreKit authentication for iOS/macOS apps
            let provider = StoreKitAuthenticationProvider()
            let factory = AuthenticatedRequestBuilderFactory(
                authProvider: provider,
                configuration: .default
            )
            print("[NolockOCRClient] Automatic StoreKit authentication enabled - drop-in replacement active")
            return factory
        }
        #endif
        // Fallback to standard factory for older platforms
        return URLSessionRequestBuilderFactory()
    }()

    public static var apiResponseQueue: DispatchQueue = .main

    // MARK: - Authentication Configuration

    /// Configures the client to use StoreKit authentication
    /// - Parameters:
    ///   - productIdentifiers: Optional set of product IDs to check for active subscriptions
    ///   - configuration: Authentication configuration settings
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    public static func configureStoreKitAuthentication(
        productIdentifiers: Set<String>? = nil,
        configuration: AuthenticationConfiguration = .default
    ) {
        let provider = StoreKitAuthenticationProvider(
            configuration: configuration,
            productIdentifiers: productIdentifiers
        )

        // Configure the authentication manager
        AuthenticationManager.shared.configure(
            provider: provider,
            configuration: configuration
        )

        // Switch to authenticated request builder factory
        requestBuilderFactory = AuthenticatedRequestBuilderFactory(
            authProvider: provider,
            configuration: configuration
        )
    }

    /// Configures the client to use mock authentication for testing
    /// - Parameters:
    ///   - mockToken: The mock JWT token to use
    ///   - configuration: Authentication configuration settings
    public static func configureMockAuthentication(
        mockToken: String,
        configuration: AuthenticationConfiguration = .default
    ) {
        let provider = MockAuthenticationProvider(token: mockToken)

        // Configure the authentication manager
        AuthenticationManager.shared.configure(
            provider: provider,
            configuration: configuration
        )

        // Switch to authenticated request builder factory
        requestBuilderFactory = AuthenticatedRequestBuilderFactory(
            authProvider: provider,
            configuration: configuration
        )
    }

    /// Configures the client with a custom authentication provider
    /// - Parameters:
    ///   - provider: Custom authentication provider
    ///   - configuration: Authentication configuration settings
    public static func configureAuthentication(
        provider: AuthenticationProvider,
        configuration: AuthenticationConfiguration = .default
    ) {
        // Configure the authentication manager
        AuthenticationManager.shared.configure(
            provider: provider,
            configuration: configuration
        )

        // Switch to authenticated request builder factory
        requestBuilderFactory = AuthenticatedRequestBuilderFactory(
            authProvider: provider,
            configuration: configuration
        )
    }

}

open class RequestBuilder<T> {
    var credential: URLCredential?
    var headers: [String: String]
    public let parameters: [String: Any]?
    public let method: String
    public let URLString: String
    public let requestTask: RequestTask = RequestTask()

    /// Optional block to obtain a reference to the request's progress instance when available.
    public var onProgressReady: ((Progress) -> Void)?

    required public init(method: String, URLString: String, parameters: [String: Any]?, headers: [String: String] = [:]) {
        self.method = method
        self.URLString = URLString
        self.parameters = parameters
        self.headers = headers

        addHeaders(NolockOCRClientAPI.customHeaders)
        addCredential()
    }

    open func addHeaders(_ aHeaders: [String: String]) {
        for (header, value) in aHeaders {
            headers[header] = value
        }
    }

    @discardableResult
    open func execute(_ apiResponseQueue: DispatchQueue = NolockOCRClientAPI.apiResponseQueue, _ completion: @escaping (_ result: Swift.Result<Response<T>, ErrorResponse>) -> Void) -> RequestTask {
        return requestTask
    }

    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    @discardableResult
    open func execute() async throws -> Response<T> {
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                self.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            self.requestTask.cancel()
        }
    }
    
    public func addHeader(name: String, value: String) -> Self {
        if !value.isEmpty {
            headers[name] = value
        }
        return self
    }

    open func addCredential() {
        credential = NolockOCRClientAPI.credential
    }
}

public protocol RequestBuilderFactory {
    func getNonDecodableBuilder<T>() -> RequestBuilder<T>.Type
    func getBuilder<T: Decodable>() -> RequestBuilder<T>.Type
}
